name: Build Multi-Platform

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds
          - os: Linux
            arch: x86_64
            runner: ubuntu-latest
            
          - os: Linux
            arch: armv8
            runner: ubuntu-latest
            
          # macOS builds
          - os: macOS
            arch: x86_64
            runner: macos-13  # Intel runner
            
          - os: macOS
            arch: armv8
            runner: macos-latest  # ARM64 runner (M1/M2)
            
          # Windows builds
          - os: Windows
            arch: x86_64
            runner: windows-latest
            
          - os: Windows
            arch: armv8
            runner: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Build application
        run: conan build . --build=missing -s compiler.cppstd=17

#      - name: Run unit tests (Done by step above, but manually here for reference)
#        run: ctest --preset conan-release